#!/usr/bin/env python3
"""Regenerate the embedded county data in county_normalization.py.

Pulls the canonical city → county mapping from the U.S. Census Bureau ANSI
INCITS reference file for Indiana, then emits a Python data file that
`county_normalization.py` consumes.

Run this manually whenever the source data needs refreshing (e.g., after
the Census Bureau publishes new ANSI codes). The generated file is
checked into the repo so production builds don't depend on the network.

Source: https://www2.census.gov/geo/docs/reference/codes2020/place/st18_in_place2020.txt
"""

import re
import urllib.request
import ssl
from pathlib import Path

CENSUS_URL = (
    "https://www2.census.gov/geo/docs/reference/codes2020/place/"
    "st18_in_place2020.txt"
)
OUTPUT = Path(__file__).parent / "county_data.py"

SUFFIX_RE = re.compile(
    r"\s+(town|city|CDP|village|borough)(\s*\(balance\))?$",
    re.IGNORECASE,
)


def fetch_census() -> dict[str, str]:
    ctx = ssl.create_default_context()
    req = urllib.request.Request(CENSUS_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30, context=ctx) as r:
        data = r.read().decode("latin-1")

    city_to_county: dict[str, str] = {}
    for line in data.splitlines()[1:]:
        parts = line.split("|")
        if len(parts) < 9:
            continue
        name, counties_str = parts[4], parts[8].strip()
        if not counties_str:
            continue
        clean = SUFFIX_RE.sub("", name).strip()
        # First county wins for multi-county places (separator is `~~~`).
        primary = (
            counties_str.split("~~~")[0]
            .split(",")[0]
            .strip()
            .replace(" County", "")
        )
        if clean and primary and clean not in city_to_county:
            city_to_county[clean] = primary
    return city_to_county


def write_data_file(city_to_county: dict[str, str]) -> None:
    lines = [
        '"""AUTOGENERATED by build_county_data.py — do not edit by hand.',
        '',
        'Source: U.S. Census Bureau 2020 ANSI INCITS codes for Indiana places.',
        f'Cities: {len(city_to_county)}',
        '"""',
        '',
        'CITY_TO_COUNTY: dict[str, str] = {',
    ]
    for city in sorted(city_to_county):
        lines.append(f'    {city!r}: {city_to_county[city]!r},')
    lines.append('}')
    lines.append('')
    OUTPUT.write_text('\n'.join(lines))
    print(f"Wrote {OUTPUT} ({len(city_to_county)} cities)")


def main() -> None:
    print(f"Fetching {CENSUS_URL}...")
    data = fetch_census()
    write_data_file(data)


if __name__ == "__main__":
    main()
