#!/usr/bin/env python3
"""Generate a TypeScript county-normalization module for an Astro site.

The TS file is the runtime artifact used by .astro templates to build
contractor → county links. It MUST stay in sync with normalize_county.py
(the Python equivalent used by data-write scripts) — this script keeps
them in sync by generating the TS from the canonical Python data.

Usage:
    python3 build_county_ts.py path/to/site/src/lib/county.ts

If no path is given, writes to stdout.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from normalize_county import all_canonical_counties, all_aliases


HEADER = """// AUTOGENERATED by ~/sites/ipla-data/build_county_ts.py — do not edit by hand.
// Mirrors normalize_county.py so data scripts and Astro templates agree
// on canonical county names and slugs.
//
// To add a new alias, edit normalize_county.py then re-run:
//   python3 ~/sites/ipla-data/build_county_ts.py <this-file-path>

"""


def emit() -> str:
    canonical = all_canonical_counties()
    aliases = all_aliases()

    lines = [HEADER.rstrip(), ""]
    lines.append("// Canonical county → slug map.")
    lines.append("const CANONICAL_TO_SLUG: Record<string, string> = {")
    for name, slug in canonical:
        lines.append(f"  {_q(name)}: {_q(slug)},")
    lines.append("};")
    lines.append("")

    lines.append("// Lower-cased alias → canonical-display map.")
    lines.append("const ALIAS_TO_CANONICAL: Record<string, string> = {")
    # Build the full alias table: every canonical maps to itself (lowercased)
    # plus every alias maps to its canonical target.
    full: dict[str, str] = {}
    for name, _ in canonical:
        full[name.strip().lower()] = name
    for alias, target in aliases.items():
        full[alias.strip().lower()] = target
    for k in sorted(full):
        lines.append(f"  {_q(k)}: {_q(full[k])},")
    lines.append("};")
    lines.append("")

    lines.append(_FUNCTION_BODY)
    return "\n".join(lines) + "\n"


def _q(s: str) -> str:
    """Emit a JSON/TS string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


_FUNCTION_BODY = """\
function normalizeKey(value: string): string {
  return value.trim().replace(/\\s+/g, " ").toLowerCase();
}

/**
 * Resolve any county name variant to its canonical display form.
 * Returns null for empty / "Unknown" / unrecognized input.
 */
export function normalizeCounty(value: string | null | undefined): string | null {
  if (!value) return null;
  let cleaned = value.trim().replace(/[,.]+$/, "").trim();
  if (!cleaned || cleaned.toLowerCase() === "unknown") return null;
  // Strip trailing " County" if present.
  cleaned = cleaned.replace(/\\s+county\\s*$/i, "").trim();
  return ALIAS_TO_CANONICAL[normalizeKey(cleaned)] ?? null;
}

/**
 * Resolve any county name variant to its canonical URL slug, or null
 * if the input is unrecognized. Callers MUST NOT render a link when
 * this returns null (otherwise the link will 404).
 */
export function countySlug(value: string | null | undefined): string | null {
  const canonical = normalizeCounty(value);
  return canonical ? CANONICAL_TO_SLUG[canonical] ?? null : null;
}
"""


def main() -> None:
    out = emit()
    if len(sys.argv) > 1:
        target = Path(sys.argv[1])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(out)
        print(f"Wrote {target}")
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
